version: '3'
services:
  nginx:
    platform: 'linux/amd64'
    image: toshihikofujii/phpzero:nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php
    

  php:
    image: toshihikofujii/phpzero:latest
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - db

  db:
    platform: 'linux/amd64'
    image: toshihikofujii/phpzero:mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: shop
      MYSQL_USER: zero
      MYSQL_PASSWORD: secret
      DB_SOCKET: /var/run/mysqld/mysqld.sock
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql


  phpmyadmin:
    platform: 'linux/amd64'
    image: toshihikofujii/phpzero:phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=zero
      - PMA_PASSWORD=secret
    ports:
      - 8888:80
    depends_on:
      - db
